rfile. If not specified, the default escape character is
\
.
The escape character is used both to escape characters in a line, and to
escape a newline. This allows a Dockerfile instruction to
span multiple lines. Note that regardless of whether the
escape
parser
directive is included in a Dockerfile, escaping is not performed in
a
RUN
command, except at the end of a line.
Setting the escape character to
`
is especially useful on
Windows
, where
\
is the directory path separator.
`
is consistent
