ds a
user could call on the command line to assemble an image. This page describes
the commands you can use in a Dockerfile.
Overview
The Dockerfile supports the following instructions:
Instruction
Description
ADD
Add local or remote files and directories.
ARG
Use build-time variables.
CMD
Specify default commands.
COPY
Copy files and directories.
ENTRYPOINT
Specify default executable.
ENV
Set environment variables.
EXPOSE
Describe which ports your application is listening on.
FROM
Create a new 