this and you should use
it instead, as it enables setting any metadata you require, and can be viewed
easily, for example with
docker inspect
. To set a label corresponding to the
MAINTAINER
field you could use:
LABEL
org.opencontainers.image.authors
=
"SvenDowideit@home.org.au"
This will then be visible from
docker inspect
with the other labels.
EXPOSE
EXPOSE
<port
>
[
<port>/<protocol>...
]
The
EXPOSE
instruction informs Docker that the container listens on the
specified network ports at runti