seful on Windows where there are
two commonly used and quite different native shells:
cmd
and
powershell
, as
well as alternate shells available including
sh
.
The
SHELL
instruction can appear multiple times. Each
SHELL
instruction overrides
all previous
SHELL
instructions, and affects all subsequent instructions. For example:
FROM
microsoft/windowsservercore
# Executed as cmd /S /C echo default
RUN
echo
default
# Executed as cmd /S /C powershell -command Write-Host default
RUN
powershell -comma