error
message, rather the file will simply be copied to the destination.
Adding files from a URL
In the case where source is a remote file URL, the destination will have
permissions of 600. If the HTTP response contains a
Last-Modified
header, the
timestamp from that header will be used to set the
mtime
on the destination
file. However, like any other file processed during an
ADD
,
mtime
isn't
included in the determination of whether or not the file has changed and the
cache should be updated.
I