 name exists at the destination, an error is raised.
If you pass a Dockerfile through stdin to the build (
docker build - < Dockerfile
), there is no build context. In this case, you can only use the
COPY
instruction to copy files from other stages, named contexts, or images,
using the
--from
flag
. You can also pass a tar archive
through stdin: (
docker build - < archive.tar
), the Dockerfile at the root of
the archive and the rest of the archive will be used as the context of the
build.
When u