ultiple device configurations:
vendor1.com/device
: request the first device found for this vendor
vendor1.com/device=foo
: request a specific device
vendor1.com/device=*
: request all devices for this vendor
class1
: request devices by
org.mobyproject.buildkit.device.class
annotation
Note
Annotations are supported by the CDI specification since 0.6.0.
Note
To automatically allow all devices registered in the CDI specification, you
can set the
org.mobyproject.buildkit.device.autoallow
annotation