ne
escapes
, or
with
heredocs
:
RUN
<<EOF
apt-get update
apt-get install -y curl
EOF
The available
[OPTIONS]
for the
RUN
instruction are:
Option
Minimum Dockerfile version
--device
1.14-labs
--mount
1.2
--network
1.3
--security
1.20
Cache invalidation for RUN instructions
The cache for
RUN
instructions isn't invalidated automatically during
the next build. The cache for an instruction like
RUN apt-get dist-upgrade -y
will be reused during the next build. The
cache for
RUN
instructions can be inv