=
"value1"
\
multi.label2
=
"value2"
\
other
=
"value3"
Note
Be sure to use double quotes and not single quotes. Particularly when you are
using string interpolation (e.g.
LABEL example="foo-$ENV_VAR"
), single
quotes will take the string as is without unpacking the variable's value.
Labels included in base images (images in the
FROM
line) are inherited by
your image. If a label already exists but with a different value, the
most-recently-applied value overrides any previously-set value.
In a mu