age_version
RUN
The
RUN
instruction will execute any commands to create a new layer on top of
the current image. The added layer is used in the next step in the Dockerfile.
RUN
has two forms:
# Shell form:
RUN
[
OPTIONS
]
<command> ...
# Exec form:
RUN
[
OPTIONS
]
[
"<command>"
, ...
]
For more information about the differences between these two forms, see
shell or exec forms
.
The shell form is most commonly used, and lets you break up longer
instructions into multiple lines, either using newli