e
$
docker run -p 80:80/tcp -p 80:80/udp ...
To set up port redirection on the host system, see
using the -P flag
.
The
docker network
command supports creating networks for communication among
containers without the need to expose or publish specific ports, because the
containers connected to the network can communicate with each other over any
port. For detailed information, see the
overview of this feature
.
ENV
ENV
<key>
=
<value>
[
<key>
=
<value>...
]
The
ENV
instruction sets the environme