lt-in build args
Impact on build caching
ONBUILD
Copy or mount from stage, image, or context
ONBUILD limitations
STOPSIGNAL
HEALTHCHECK
SHELL
Here-Documents
Example: Running a multi-line script
Example: Creating inline files
Dockerfile examples