ing
ARG
variables are not persisted into the built image as
ENV
variables are.
However,
ARG
variables do impact the build cache in similar ways. If a
Dockerfile defines an
ARG
variable whose value is different from a previous
build, then a "cache miss" occurs upon its first usage, not its definition. In
particular, all
RUN
instructions following an
ARG
instruction use the
ARG
variable implicitly (as an environment variable), thus can cause a cache miss.
All predefined
ARG
variables are exempt fr