ms:
INSTRUCTION ["executable","param1","param2"]
(exec form)
INSTRUCTION command param1 param2
(shell form)
The exec form makes it possible to avoid shell string munging, and to invoke
commands using a specific command shell, or any other executable. It uses a
JSON array syntax, where each element in the array is a command, flag, or
argument.
The shell form is more relaxed, and emphasizes ease of use, flexibility, and
readability. The shell form automatically uses a command shell, whereas the
ex