file:1
FROM
alpine
ADD
--keep-git-dir
=
true
https://github.com/moby/buildkit.git#v0.10.1 /buildkit
ADD --checksum
ADD
[
--checksum
=
<hash>
]
<src> ... <dir>
The
--checksum
flag lets you verify the checksum of a remote Git or HTTP
resource:
For Git sources, the checksum is the commit SHA. It can be the full commit
SHA or match on the prefix (1 or more characters).
For HTTP sources, the checksum is the SHA-256 content digest, formatted as
sha256:<hash>
. SHA-256 is the only supported hash algori