environment:
FROM
ubuntu
AS
base
RUN
apt-get update
&&
apt-get install -y shared-tooling
FROM
base
AS
dev
RUN
apt-get install -y dev-tooling
FROM
base
AS
prod
COPY
--from
=
build /app /app
The
tag
or
digest
values are optional. If you omit either of them, the
builder assumes a
latest
tag by default. The builder returns an error if it
can't find the
tag
value.
The optional
--platform
flag can be used to specify the platform of the image
in case
FROM
references a multi-platform image. For example,