ginx
with its default
content, listening on port 80:
$
docker run -i -t --rm -p 80:80 nginx
Command line arguments to
docker run <image>
will be appended after all
elements in an exec form
ENTRYPOINT
, and will override all elements specified
using
CMD
.
This allows arguments to be passed to the entry point, i.e.,
docker run <image> -d
will pass the
-d
argument to the entry point. You can override
the
ENTRYPOINT
instruction using the
docker run --entrypoint
flag.
The shell form of
ENTRYPOINT
ign