shebang header can be used to define an interpreter.
# syntax=docker/dockerfile:1
FROM
python:3.6
RUN
<<EOT
#!/usr/bin/env python
print
(
"hello world"
)
EOT
More complex examples may use multiple here-documents.
# syntax=docker/dockerfile:1
FROM
alpine
RUN
<<FILE1 cat > file1 && <<FILE
2
cat > file2
I am
first
FILE1
I am
second
FILE2
Example: Creating inline files
With
COPY
instructions, you can replace the source parameter with a here-doc
indicator to write the contents of the here-document di