estination. For example, to add two files,
file1.txt
and
file2.txt
, from the build context to
/usr/src/things/
in
the build container:
ADD
file1.txt file2.txt /usr/src/things/
If you specify multiple source files, either directly or using a wildcard, then
the destination must be a directory (must end with a slash
/
).
To add files from a remote location, you can specify a URL or the address of a
Git repository as the source. For example:
ADD
https://example.com/archive.zip /usr/src/things/
ADD
