ownstream builder looks for
ONBUILD
triggers, and executes
them in the same order they were registered. If any of the triggers
fail, the
FROM
instruction is aborted which in turn causes the
build to fail. If all triggers succeed, the
FROM
instruction
completes and the build continues as usual.
Triggers are cleared from the final image after being executed. In
other words they aren't inherited by "grand-children" builds.
For example you might add something like this:
ONBUILD
ADD
. /app/src
ONBUIL