lt. Eg
linux/amd64
,
linux/arm/v7
,
windows/amd64
.
TARGETOS
- OS component of TARGETPLATFORM
TARGETARCH
- architecture component of TARGETPLATFORM
TARGETVARIANT
- variant component of TARGETPLATFORM
BUILDPLATFORM
- platform of the node performing the build.
BUILDOS
- OS component of BUILDPLATFORM
BUILDARCH
- architecture component of BUILDPLATFORM
BUILDVARIANT
- variant component of BUILDPLATFORM
These arguments are defined in the global scope so are not automatically
available inside build sta