r -x
.
The result is the union of:
Whatever existed at the destination path, and
The contents of the source tree, with conflicts resolved in favor of the
content being added, on a file-by-file basis.
Note
Whether a file is identified as a recognized compression format or not is
done solely based on the contents of the file, not the name of the file. For
example, if an empty file happens to end with
.tar.gz
this isn't recognized
as a compressed file and doesn't generate any kind of decompression 