ile mode for new cache directory in octal. Default
0755
.
uid
User ID for new cache directory. Default
0
.
gid
Group ID for new cache directory. Default
0
.
Contents of the cache directories persists between builder invocations without
invalidating the instruction cache. Cache mounts should only be used for better
performance. Your build should work with any contents of the cache directory as
another build may overwrite the files or GC may clean it if more storage space
is needed.
Example: cache