at isn't a parser directive.
# unknowndirective=value
# syntax=value
Non line-breaking whitespace is permitted in a parser directive. Hence, the
following lines are all treated identically:
#directive=value
# directive =value
#	directive= value
# directive = value
#	  dIrEcTiVe=value
syntax
Use the
syntax
parser directive to declare the Dockerfile syntax version to
use for the build. If unspecified, BuildKit uses a bundled version of the
Dockerfile frontend. Declaring a syntax version lets you a