
ENV
instructions:
FROM
ubuntu
ARG
CONT_IMG_VER
ENV
CONT_IMG_VER
=
${
CONT_IMG_VER
:-
v1
.0.0
}
RUN
echo
$CONT_IMG_VER
Unlike an
ARG
instruction,
ENV
values are always persisted in the built
image. Consider a docker build without the
--build-arg
flag:
$
docker build .
Using this Dockerfile example,
CONT_IMG_VER
is still persisted in the image but
its value would be
v1.0.0
as it is the default set in line 3 by the
ENV
instruction.
The variable expansion technique in this example allows you to pas