ID output by the commit before each new
FROM
instruction. Each
FROM
instruction clears any state created by previous
instructions.
Optionally a name can be given to a new build stage by adding
AS name
to the
FROM
instruction. The name can be used in subsequent
FROM <name>
,
COPY --from=<name>
,
and
RUN --mount=type=bind,from=<name>
instructions
to refer to the image built in this stage.
Using a previous build stage as the base for a subsequent stage is a common
pattern for sharing a common base 