
destination
1
Mount path.
size
Specify an upper limit on the size of the filesystem.
RUN --mount=type=secret
This mount type allows the build container to access secret values, such as
tokens or private keys, without baking them into the image.
By default, the secret is mounted as a file. You can also mount the secret as
an environment variable by setting the
env
option.
Option
Description
id
ID of the secret. Defaults to basename of the target path.
target
,
dst
,
destination
Mount the secret 