     STAT   VSZ %VSZ %CPU COMMAND
1     0 root     R     3164   0%   0% top -b
Which exits cleanly on
docker stop
:
$
/usr/bin/time docker stop
test
test
real	0m 0.20s
user	0m 0.02s
sys	0m 0.04s
If you forget to add
exec
to the beginning of your
ENTRYPOINT
:
FROM
ubuntu
ENTRYPOINT
top -b
CMD
-- --ignored-param1
You can then run it (giving it a name for the next step):
$
docker run -it --name
test
top --ignored-param2
top - 13:58:24 up 17 min,  0 users,  load average: 0.00, 0.00, 0.00
Tasks:   2 