
Build stage, context, or image name for the root of the source. Defaults to the build context.
rw
,
readwrite
Allow writes on the mount. Written data will be discarded after the
RUN
instruction completes and will not be committed to the image layer.
RUN --mount=type=cache
This mount type allows the build container to cache directories for compilers
and package managers.
Option
Description
id
Optional ID to identify separate/different caches. Defaults to value of
target
.
target
,
dst
,
destinat