tainer start
docker container stats
docker container stop
docker container top
docker container unpause
docker container update
docker container wait
docker context
docker context create
docker context export
docker context import
docker context inspect
docker context ls
docker context rm
docker context show
docker context update
docker context use
docker debug
docker desktop
docker desktop diagnose
docker desktop disable
docker desktop disable model-runner
docker desktop enable
docker desktop e