ly invoke a command shell. This means
that normal shell processing, such as variable substitution, doesn't happen.
For example,
RUN [ "echo", "$HOME" ]
won't handle variable substitution for
$HOME
.
If you want shell processing then either use the shell form or execute a shell
directly with the exec form, for example:
RUN [ "sh", "-c", "echo $HOME" ]
.
When using the exec form and executing a shell directly, as in the case for the
shell form, it's the shell that's doing the environment variable 