OPY
<<-EOT /script.sh
echo
"hello
${
FOO
}
"
EOT
ENTRYPOINT
ash /script.sh
In this case, file script prints "hello bar", because the variable is expanded
when the
COPY
instruction gets executed.
$
docker build -t heredoc .
$
docker run heredoc
hello bar
If instead you were to quote any part of the here-document word
EOT
, the
variable would not be expanded at build-time.
# syntax=docker/dockerfile:1
FROM
alpine
ARG
FOO
=
bar
COPY
<<-
"EOT"
/script.sh
echo
"hello
${
FOO
}
"
EOT
ENTRYPOINT
ash /sc