ile shows using the
ENTRYPOINT
to run Apache in the
foreground (i.e., as
PID 1
):
FROM
debian:stable
RUN
apt-get update
&&
apt-get install -y --force-yes apache2
EXPOSE
80
443
VOLUME
[
"/var/www"
,
"/var/log/apache2"
,
"/etc/apache2"
]
ENTRYPOINT
[
"/usr/sbin/apache2ctl"
,
"-D"
,
"FOREGROUND"
]
If you need to write a starter script for a single executable, you can ensure that
the final executable receives the Unix signals by using
exec
and
gosu
commands:
#!/usr/bin/env bash
set
-e
if
[
"
$1
"
=
