ot case-sensitive. However, convention is for them to
be UPPERCASE to distinguish them from arguments more easily.
Docker runs instructions in a Dockerfile in order. A Dockerfile
must
begin with a
FROM
instruction
. This may be after
parser
directives
,
comments
, and globally scoped
ARGs
. The
FROM
instruction specifies the
base
image
from which you are
building.
FROM
may only be preceded by one or more
ARG
instructions, which
declare arguments that are used in
FROM
lines in the Dockerfile.
Bui