entrypoint
flag.
The shell form of
ENTRYPOINT
ignores any
CMD
or
docker run
command line
arguments. It also starts your
ENTRYPOINT
as a subcommand of
/bin/sh -c
,
which does not pass signals. This means that the executable will not be the
container's
PID 1
, and will not receive Unix signals. In this case, your
executable doesn't receive a
SIGTERM
from
docker stop <container>
.
Only the last
ENTRYPOINT
instruction in the Dockerfile will have an effect.
Exec form ENTRYPOINT example
You can use th