er
from an image.
You can specify
CMD
instructions using
shell or exec forms
:
CMD ["executable","param1","param2"]
(exec form)
CMD ["param1","param2"]
(exec form, as default parameters to
ENTRYPOINT
)
CMD command param1 param2
(shell form)
There can only be one
CMD
instruction in a Dockerfile. If you list more than
one
CMD
, only the last one takes effect.
The purpose of a
CMD
is to provide defaults for an executing container. These
defaults can include an executable, or they can omit the execu