consisting of only one
src
entry, usually it is more beneficial
to keep the layer count in the resulting image as low as possible. Therefore,
with the
--parents
flag, the Buildkit is capable of packing multiple
COPY
instructions together, keeping the directory structure intact.
COPY --exclude
COPY
[
--exclude
=
<path> ...
]
<src> ... <dest>
The
--exclude
flag lets you specify a path expression for files to be excluded.
The path expression follows the same format as
<src>
,
supporting wildcards a