r UID) and optionally the user
group (or GID) to use as the default user and group for the remainder of the
current stage. The specified user is used for
RUN
instructions and at
runtime runs the relevant
ENTRYPOINT
and
CMD
commands.
Note that when specifying a group for the user, the user will have
only
the
specified group membership. Any other configured group memberships will be ignored.
Warning
When the user doesn't have a primary group then the image (or the next
instructions) will be run wi