d placed at
the specified destination. See
Adding files from a URL
.
If
<src>
is a Git repository, the repository is cloned to the specified
destination. See
Adding files from a Git repository
.
Adding files from the build context
Any relative or local path that doesn't begin with a
http://
,
https://
, or
git@
protocol prefix is considered a local file path. The local file path is
relative to the build context. For example, if the build context is the current
directory,
ADD file.txt /
adds the 