ese arguments inside the build stage redefine it without value.
For example:
FROM
alpine
ARG
TARGETPLATFORM
RUN
echo
"I'm building for
$TARGETPLATFORM
"
BuildKit built-in build args
Arg
Type
Description
BUILDKIT_BUILD_NAME
String
Override the build name shown in
buildx history
command
and
Docker Desktop Builds view
.
BUILDKIT_CACHE_MOUNT_NS
String
Set optional cache ID namespace.
BUILDKIT_CONTEXT_KEEP_GIT_DIR
Bool
Trigger Git context to keep the
.git
directory.
BUILDKIT_INLINE_CACHE
2
Bool
Inlin