 The value can be a JSON array,
VOLUME ["/var/log/"]
, or a plain
string with multiple arguments, such as
VOLUME /var/log
or
VOLUME /var/log /var/db
. For more information/examples and mounting instructions via the
Docker client, refer to
Share Directories via Volumes
documentation.
The
docker run
command initializes the newly created volume with any data
that exists at the specified location within the base image. For example,
consider the following Dockerfile snippet:
FROM
ubuntu
RUN
mkdir /my