 convention. Values for a directive are case-sensitive and
must be written in the appropriate case for the directive. For example,
#check=skip=jsonargsrecommended
is invalid because the check name must use
Pascal case, not lowercase. It's also conventional to include a blank line
following any parser directives. Line continuation characters aren't supported
in parser directives.
Due to these rules, the following examples are all invalid:
Invalid due to line continuation:
# direc \
tive
=
value
I