than
C:
Changing the volume from within the Dockerfile
: If any build steps change the
data within the volume after it has been declared, those changes will be discarded
when using the legacy builder. When using Buildkit, the changes will instead be kept.
JSON formatting
: The list is parsed as a JSON array.
You must enclose words with double quotes (
"
) rather than single quotes (
'
).
The host directory is declared at container run-time
: The host directory
(the mountpoint) is, by its nature,