is the directory path separator.
`
is consistent
with
Windows PowerShell
.
Consider the following example which would fail in a non-obvious way on
Windows. The second
\
at the end of the second line would be interpreted as an
escape for the newline, instead of a target of the escape from the first
\
.
Similarly, the
\
at the end of the third line would, assuming it was actually
handled as an instruction, cause it be treated as a line continuation. The result
of this Dockerfile is that second and