s://example.com/archive.zip /usr/src/things/
ADD
git@github.com:user/repo.git /usr/src/things/
BuildKit detects the type of
<src>
and processes it accordingly.
If
<src>
is a local file or directory, the contents of the directory are
copied to the specified destination. See
Adding files from the build context
.
If
<src>
is a local tar archive, it is decompressed and extracted to the
specified destination. See
Adding local tar archives
.
If
<src>
is a URL, the contents of the URL are downloaded an