vol
RUN
echo
"hello world"
> /myvol/greeting
VOLUME
/myvol
This Dockerfile results in an image that causes
docker run
to
create a new mount point at
/myvol
and copy the
greeting
file
into the newly created volume.
Notes about specifying volumes
Keep the following things in mind about volumes in the Dockerfile.
Volumes on Windows-based containers
: When using Windows-based containers,
the destination of a volume inside the container must be one of:
a non-existing or empty directory
a drive other 