lang
RUN
--mount
=
type
=
cache,target
=
/root/.cache/go-build
\
go build ...
Example: cache apt packages
# syntax=docker/dockerfile:1
FROM
ubuntu
RUN
rm -f /etc/apt/apt.conf.d/docker-clean
;
echo
'Binary::apt::APT::Keep-Downloaded-Packages "true";'
> /etc/apt/apt.conf.d/keep-cache
RUN
--mount
=
type
=
cache,target
=
/var/cache/apt,sharing
=
locked
\
--mount
=
type
=
cache,target
=
/var/lib/apt,sharing
=
locked
\
apt-get update
&&
apt-get --no-install-recommends install -y gcc
Apt needs exclusiv