file.
For example:
ENV
DIRPATH
=
/path
WORKDIR
$DIRPATH/$DIRNAME
RUN
pwd
The output of the final
pwd
command in this Dockerfile would be
/path/$DIRNAME
If not specified, the default working directory is
/
. In practice, if you aren't building a Dockerfile from scratch (
FROM scratch
),
the
WORKDIR
may likely be set by the base image you're using.
Therefore, to avoid unintended operations in unknown directories, it's best practice to set your
WORKDIR
explicitly.
ARG
ARG
<name>
[=
<default value>
