
=
10:11 files* /somedir/
COPY
--chown
=
myuser:mygroup --chmod
=
644
files* /somedir/
When using names instead of numeric IDs, BuildKit resolves them using
/etc/passwd
and
/etc/group
in the container's root filesystem. If these
files are missing or don't contain the specified names, the build fails.
Numeric IDs don't require this lookup.
The
--chown
flag is not supported when building Windows containers.
COPY --link
COPY
[
--link
[=
<boolean>
]]
<src> ... <dest>
Enabling this flag in
COPY
or
AD