t
docker stop
will signal any long running
ENTRYPOINT
executable
correctly, you need to remember to start it with
exec
:
FROM
ubuntu
ENTRYPOINT
exec
top -b
When you run this image, you'll see the single
PID 1
process:
$
docker run -it --rm --name
test
top
Mem: 1704520K used, 352148K free, 0K shrd, 0K buff, 140368121167873K cached
CPU:   5% usr   0% sys   0% nic  94% idle   0% io   0% irq   0% sirq
Load average: 0.08 0.03 0.05 2/98 6
PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
1     0 root   