
Dog
ENV
MY_CAT
=
fluffy
The
ENV
instruction allows for multiple
<key>=<value> ...
variables to be set
at one time, and the example below will yield the same net results in the final
image:
ENV
MY_NAME
=
"John Doe"
MY_DOG
=
Rex
\
The
\
Dog
\
MY_CAT
=
fluffy
The environment variables set using
ENV
will persist when a container is run
from the resulting image. You can view the values using
docker inspect
, and
change them using
docker run --env <key>=<value>
.
A stage inherits any environment vari