ion
1
Mount path.
ro
,
readonly
Read-only if set.
sharing
One of
shared
,
private
, or
locked
. Defaults to
shared
. A
shared
cache mount can be used concurrently by multiple writers.
private
creates a new mount if there are multiple writers.
locked
pauses the second writer until the first one releases the mount.
from
Build stage, context, or image name to use as a base of the cache mount. Defaults to empty directory.
source
Subpath in the
from
to mount. Defaults to the root of the
from
.
mode
F