stination doesn't exist, it's created, along with all missing directories
in its path.
If the source is a file, and the destination doesn't end with a trailing slash,
the source file will be written to the destination path as a file.
COPY --from
By default, the
COPY
instruction copies files from the build context. The
COPY --from
flag lets you copy files from an image, a build stage,
or a named context instead.
COPY
[
--from
=
<image
|
stage
|
context>
]
<src> ... <dest>
To copy from a build sta