ries for
src
entries. This flag defaults to
false
.
# syntax=docker/dockerfile:1
FROM
scratch
COPY
./x/a.txt ./y/a.txt /no_parents/
COPY
--parents ./x/a.txt ./y/a.txt /parents/
# /no_parents/a.txt
# /parents/x/a.txt
# /parents/y/a.txt
This behavior is similar to the
Linux
cp
utility's
--parents
or
rsync
--relative
flag.
As with Rsync, it is possible to limit which parent directories are preserved by
inserting a dot and a slash (
./
) into the source path. If such point exists, only parent
direct