.host
flag or in
buildkitd config
,
and for a build request with
--allow network.host
flag
.
RUN --security
RUN
--security
=
<sandbox
|
insecure>
The default security mode is
sandbox
.
With
--security=insecure
, the builder runs the command without sandbox in insecure
mode, which allows to run flows requiring elevated privileges (e.g. containerd).
This is equivalent to running
docker run --privileged
.
Warning
In order to access this feature, entitlement
security.insecure
should be
enabled when 