${variable/pattern/replacement}
replace the first occurrence of
pattern
in
variable
with
replacement
string
=
foobarbaz
echo
${
string
/ba/fo
}
# fooforbaz
${variable//pattern/replacement}
replaces all occurrences of
pattern
in
variable
with
replacement
string
=
foobarbaz
echo
${
string
//ba/fo
}
# fooforfoz
In all cases,
word
can be any string, including additional environment
variables.
pattern
is a glob pattern where
?
matches any single character
and
*
any number of characters (including zer