 device.
Example: CUDA-Powered LLaMA Inference
In this example we use the
--device
flag to run
llama.cpp
inference using
an NVIDIA GPU device through CDI:
# syntax=docker/dockerfile:1-labs
FROM
scratch
AS
model
ADD
https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf /model.gguf
FROM
scratch
AS
prompt
COPY
<<EOF prompt.txt
Q: Generate  a list of
10
unique biggest countries by population in JSON with their estimated poulation in
1900
and 2024.