
--exclude
1.19
The
ADD
instruction copies new files or directories from
<src>
and adds
them to the filesystem of the image at the path
<dest>
. Files and directories
can be copied from the build context, a remote URL, or a Git repository.
The
ADD
and
COPY
instructions are functionally similar, but serve slightly different purposes.
Learn more about the
differences between
ADD
and
COPY
.
Source
You can specify multiple source files or directories with
ADD
. The last
argument must always be the d