
/bin/sh -c exec_entry p1_entry
exec_entry p1_entry exec_cmd p1_cmd
CMD exec_cmd p1_cmd
/bin/sh -c exec_cmd p1_cmd
/bin/sh -c exec_entry p1_entry
exec_entry p1_entry /bin/sh -c exec_cmd p1_cmd
Note
If
CMD
is defined from the base image, setting
ENTRYPOINT
will
reset
CMD
to an empty value. In this scenario,
CMD
must be defined in the
current image to have a value.
VOLUME
VOLUME
[
"/data"
]
The
VOLUME
instruction creates a mount point with the specified name
and marks it as holding externally moun