ntainer too
# USE the trap if you need to also do manual cleanup after the service is stopped,
#     or need to start multiple services in the one container
trap
"echo TRAPed signal"
HUP INT QUIT TERM
# start service in background here
/usr/sbin/apachectl start
echo
"[hit enter key to exit] or run 'docker stop <container>'"
read
# stop service and clean up here
echo
"stopping apache"
/usr/sbin/apachectl stop
echo
"exited
$0
"
If you run this image with
docker run -it --rm -p 80:80 --name test ap