tion path
becomes the filename of the file downloaded from the URL. For example,
ADD http://example.com/foo /bar
creates the file
/bar
.
If your URL files are protected using authentication, you need to use
RUN wget
,
RUN curl
or use another tool from within the container as the
ADD
instruction
doesn't support authentication.
Secrets
You can use the
HTTP_AUTH_HEADER_<host>
and
HTTP_AUTH_TOKEN_<host>
secrets
to set credentials for remote sources. For more information, see
Build secrets
.
Adding f