 Answer only newline formatted JSON with keys
"country"
,
"population_1900"
,
"population_2024"
with
10
items.
A:
[
{
EOF
FROM
ghcr.io/ggml-org/llama.cpp:full-cuda-b5124
RUN
--device
=
nvidia.com/gpu
=
all
\
--mount
=
from
=
model,target
=
/models
\
--mount
=
from
=
prompt,target
=
/tmp
\
./llama-cli -m /models/model.gguf -no-cnv -ngl
99
-f /tmp/prompt.txt
RUN --mount
RUN
--mount
=[
type
=
<TYPE>
][
,option
=
<value>
[
,option
=
<value>
]
...
]
RUN --mount
allows you to create filesystem mounts 