s:
RUN
[
"powershell"
,
"-command"
,
"Execute-MyCmdlet"
,
"-param1 \"c:\\foo.txt\""
]
While the JSON form is unambiguous and does not use the unnecessary
cmd.exe
,
it does require more verbosity through double-quoting and escaping. The alternate
mechanism is to use the
SHELL
instruction and the shell form,
making a more natural syntax for Windows users, especially when combined with
the
escape
parser directive:
# escape=`
FROM
microsoft/nanoserver
SHELL
[
"powershell"
,
"-command"
]
RUN
New-Item