de
File mode for socket in octal. Default
0600
.
uid
User ID for socket. Default
0
.
gid
Group ID for socket. Default
0
.
Example: access to GitLab
# syntax=docker/dockerfile:1
FROM
alpine
RUN
apk add --no-cache openssh-client
RUN
mkdir -p -m
0700
~/.ssh
&&
ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
RUN
--mount
=
type
=
ssh
\
ssh -q -T git@gitlab.com 2>
&
1
|
tee /hello
# "Welcome to GitLab, @GITLAB_USERNAME_ASSOCIATED_WITH_SSHKEY" should be printed here
# with the type of build progress is de