s for an
ENTRYPOINT
command
or for executing an ad-hoc command in a container.
CMD
will be overridden when running the container with alternative arguments.
The table below shows what command is executed for different
ENTRYPOINT
/
CMD
combinations:
No ENTRYPOINT
ENTRYPOINT exec_entry p1_entry
ENTRYPOINT ["exec_entry", "p1_entry"]
No CMD
error, not allowed
/bin/sh -c exec_entry p1_entry
exec_entry p1_entry
CMD ["exec_cmd", "p1_cmd"]
exec_cmd p1_cmd
/bin/sh -c exec_entry p1_entry
exec_entry p1_ent