e exec form of
ENTRYPOINT
to set fairly stable default commands
and arguments and then use
CMD
to set additional defaults that are more
likely to be changed.
When combining exec form
ENTRYPOINT
with
CMD
, use the exec form of
CMD
as well. Using the shell form of
CMD
causes it to be wrapped in
/bin/sh -c
, which means the
ENTRYPOINT
receives a shell invocation as its
argument rather than the bare command and parameters. See
Understand how CMD and ENTRYPOINT interact
.
FROM
ubuntu
ENTRYPOINT
[
"to