 will be used as the context of the
build.
When using a Git repository as the build context, the permissions bits for
copied files are 644. If a file in the repository has the executable bit set,
it will have permissions set to 755. Directories have permissions set to 755.
Pattern matching
For local files, each
<src>
may contain wildcards and matching will be done
using Go's
filepath.Match
rules.
For example, to add all files and directories in the root of the build context
ending with
.png
:
CO