f remote file is a tar archive, the archive is not extracted by default. To
download and extract the archive, use the [
ADD --unpack
flag].
If the destination ends with a trailing slash, then the filename is inferred
from the URL path. For example,
ADD http://example.com/foobar /
would create
the file
/foobar
. The URL must have a nontrivial path so that an appropriate
filename can be discovered (
http://example.com
doesn't work).
If the destination doesn't end with a trailing slash, the destina